version: "3.3"
services:
  db:
    image: postgres:alpine
    container_name: local-postgres
    volumes:
      - ../services/database/scripts/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=docker
      - POSTGRES_DB=test_db
