name: typecheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run typechecks
        run: yarn typecheck
